### ISSUE TITLE
[숫자야구게임]숫자 맞추기 - Strike

### ISSUE THREAD

**Issue by nayoung511** [team24Bull/bull#1]
## 설명(Description)

Strike 기능 (값과 자릿수 확인) 구현

## 할 일(Tasks)

- [x] 랜덤 숫자 리스트, 유저 인풋 리스트, 자릿수 함수 인자로 넘겨 받기
- [x] 랜덤 숫자 리스트의 숫자의 값과 위치가 유저 인풋과 동일한지 확인하는 If 문
- [x] Return: strike의 갯수

**Comment by Jung110** [comment]
input , return 어떤 값으로 할건지 명시해 주세요

**Comment by nayoung511** [comment]
@Jung110 수정했습니다! 확인 부탁드립니다 :)

**Comment by Jung110** [comment]
Goog to GO!! 😄
