### ISSUE TITLE
숫자 맞추기 Out 기능 구현

### ISSUE THREAD

**Issue by Dahyun-K** [team24Bull/bull#2]
## 설명(Description)

user 가 입력한 숫자가 랜덤 숫자와 비교해 숫자가 없으면 out을 출력합니다.

## 할 일(Tasks)

- [x] user 숫자 받기
- [x] 숫자 비교하기
- [x] 'out' 프린트하기

**Comment by Jung110** [comment]
아주 간결하게 잘 적으셨습니다. 👍
