### ISSUE TITLE
랜덤 숫자 생성

### ISSUE THREAD

**Issue by oyj940331** [team24Bull/bull#3]
## 설명(Description)

사용자가 입력한 난이도에 따라 랜덤 숫자 생성

사용자가 난이도 (easy(3), normal(4), hard(5)) 를 입력하면
난이도에 맞는 자릿수의 랜덤 숫자 생성(중복 없이)

## 할 일(Tasks)

- [x] 사용자로부터 난이도 입력받기
- [x] 난이도에 맞는 자릿수의 중복없는 랜덤 숫자 생성
- [x] 난이도(자릿수), 생성한 랜덤 숫자 리스트 리턴

## 참조(References)

- [Bulls and Cows](https://www.mathsisfun.com/games/bulls-and-cows.html)

**Comment by Jung110** [comment]
아주 이해하기  좋게 적어 주셨습니다. ㅎㅎ
