### ISSUE TITLE
[숫자 야구] 2. input

### ISSUE THREAD

**Issue by Rehudip** [team24Bull/bull#4]
## 설명(Description)
사용자가 입력한 숫자에 따라서 그에 맞는 아웃풋을 출력할수 있는 함수.
기본적으론 숫자를 입력 받고 그 숫자를 argument로 다음 함수를 실행하게 하거나 무효한 값을 입력받으면 오류값을 출력함.
## 할 일(Tasks)
- [ ] 자릿수 input
- [ ] 유저가 입력한 숫자가 유효한지 확인하기(자릿수 일치여부, 입력값에 불순물은 없는지.)

## 참조(References)
[Bulls and Cows](https://www.mathsisfun.com/games/bulls-and-cows.html)

**Comment by Jung110** [comment]
양식에 맞추어서 적어주시면 감사하겠습니다. ㅎㅎ

**Comment by Rehudip** [comment]
> 양식에 맞추어서 적어주시면 감사하겠습니다. ㅎㅎ

@Jung110 완.

**Comment by Jung110** [comment]
감사합니다. 😄
