### ISSUE TITLE
Bulls and Cows에서 Cows를 출력하는 코드를 구현합니다.

### ISSUE THREAD

**Issue by DKIMDK** [team24Bull/bull#5]
## 설명(Description)

Cows를 출력하는 코드를 구현합니다.

출제자가 설정한 숫자 리스트를 받아 사용자의 input 리스트와 비교합니다.
리스트 안에는 있지만 인덱스 위치가 다른 숫자의 수를 세어 'Cows: n'의 형태로 출력합니다. 
변수나 함수 이름은 팀장님이 지정부탁드립니다!

## 할 일(Tasks)

- [x] 정답과 질문 받기.
- [x] 둘을 비교하여 중복이면서 위치가 다른 숫자 찾기
- [x] 출력하기

## 참조(References)

-

**Comment by nayoung511** [comment]
@Dahyun-K @DKIMDK 
저희 strike, cow, out 변수를 함수 안에 적을까요? 아니면 글로벌 변수로 생성할까요?

**Comment by Jung110** [comment]
양식에 맞게 아주 좋게 작성해주셨습니다. ㅎㅎ
